# 版本
version: "3.7"

# 服务
services:

  mongo:
    container_name: mongo
    image: mongo:2.6
    restart: always
    hostname: mongo
#    ports:
#      - 27017
#    volumes:
#      - ../dev-ops-repo/yapi/mongo:/data/db
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}

  yapi:
    container_name: yapi
    image: v7lin/yapi:test
    restart: always
    hostname: yapi
    ports:
      - 8080:3000
#    volumes:
#      - ../dev-ops-repo/yapi/init:/yapi/init
#      - ../dev-ops-repo/yapi/log:/yapi/log
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - YAPI_PORT=3000
      - YAPI_ADMINACCOUNT=admin@admin.com
      - YAPI_ADMINPASSWORD=admin
      - YAPI_DB_SERVERNAME=mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
    depends_on:
      - mongo
